<?php
$title = 'Edit contact';
$this->headTitle($title);
?>
<br/>
<ol class="breadcrumb">
    <li><a href="<?php
        echo $this->url('home');
        ?>">Home</a></li>
    <li><a href="<?php
        echo $this->url('contact');
        ?>">Contacts</a></li>
    <li class="active"><?php echo $this->escapeHtml($title); ?></li>
</ol>

<?php
$form = $this->form;
$form->setAttribute('action',
    $this->url('contact', array('action' => 'edit', 'id' => $this->id)));
//$form->setAttribute('class', 'form-horizontal');
$form->prepare();

echo $this->form()->openTag($form) . PHP_EOL;
?>
<?php foreach ($form as $element) { ?>
    <div class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
        <?php
        if ('submit' != $element->getAttribute('type') && $element->getAttribute('type') != "hidden") {
            ?>
            <label class="control-label"><?php echo $element->getLabel() ?></label>
            <?php
            $element->setAttribute('class', 'form-control')
                ->setAttribute('placeholder', $element->getLabel());
        } else {
            $element->setAttribute('class', 'btn btn-success');
        }
        echo $this->formElement($element);
        if ($this->formElementErrors($element)) : ?>
            <?php
            echo $this->formElementErrors()
                ->setMessageOpenFormat('<p class="help-block">')
                ->setMessageSeparatorString('</p><p class="help-block">')
                ->setMessageCloseString('</p>')
                ->render($element);
            ?>
        <?php endif; ?>
    </div>
<?php
}
?>

<?php echo $this->form()->closeTag() ?>
