<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sContacts Manager%s'), '<span class="zf-green">', '</span>') ?></h1>

    <p><?php echo sprintf($this->translate('Helps you to manage your contacts.')) ?></p>

    <?php if ($this->zfcUserIdentity()) { ?>
        <p><a class="btn btn-success btn-lg"
              href="<?php echo $this->url('contact') ?>"><?php echo $this->translate('Manage Contacts') ?> &raquo;</a>
        </p>
    <?php
    } else {
        ?>
        <p><a class="btn btn-success btn-lg"
              href="<?php echo $this->basePath() ?>/user/login"><?php echo $this->translate('Login') ?> &raquo;</a></p>
    <?php
    } ?>
</div>

